name: Build and Push Docker, Update Manifest

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: zxzxcx/myproject

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.TAG }}   # <- 여기 추가

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag from short SHA
        id: vars
        run: |
          TAG=TAG-${GITHUB_SHA::7}
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}

  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout manifest branch
        uses: actions/checkout@v4
        with:
          ref: manifest

      - name: Update image tag in deployment.yaml
        run: |
          TAG=${{ needs.build-and-push.outputs.tag }}  # <- 수정된 TAG 참조
          sed -i "s|${{ env.IMAGE_NAME }}:.*|${{ env.IMAGE_NAME }}:${TAG}|g" k8s/deployment.yaml

      - name: Commit and push to manifest branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image tag to ${{ needs.build-and-push.outputs.tag }}"
          git push origin manifest
